# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Shopping list' do

# Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Shopping list
  pod 'RealmSwift', '~>10'

end

